export const PRODUCTS = [
  {
    id: 1,
    name: "Adjustable Dumbbell Set",
    category: "Equipment",
    price: 120.0,
    description:
      "Adjustable dumbbell set with weights ranging from 5-50 lbs, ideal for strength training.",
    brand: "Life Pro",
    stock: 50,
    image_url:
      "https://m.media-amazon.com/images/I/81-5vsFdaJL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Whey Protein Powder",
    category: "Supplements",
    price: 45.0,
    description:
      "High-quality whey protein for muscle recovery, chocolate flavor, 2 lbs.",
    brand: "OPTIMUM NUTRITION",
    stock: 200,
    image_url:
      "https://i5.walmartimages.com/seo/Optimum-Nutrition-Gold-Standard-100-Whey-Protein-Powder-French-Vanilla-Creme-5-lb-73-Servings_9cc1f005-862c-4d5b-aa1c-2e7488e06e74.ab2aa3b1caf76cb3f9357d9c845b5974.png",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Yoga Mat",
    category: "Equipment",
    price: 25.0,
    description:
      "Non-slip yoga mat, perfect for yoga, Pilates, and other floor exercises.",
    brand: "ZenFlex",
    stock: 150,
    image_url:
      "https://img.freepik.com/premium-photo/yoga-mat-rolled-up-transparent-background-ai_894067-5924.jpg",
    rating: 4.6,
  },
  {
    id: 4,
    name: "Running Shoes",
    category: "Apparel",
    price: 80.0,
    description:
      "Lightweight running shoes with excellent cushioning for maximum comfort.",
    brand: "RunFast",
    stock: 75,
    image_url:
      "https://cdn.thewirecutter.com/wp-content/media/2023/09/running-shoes-2048px-5946.jpg?auto=webp&quality=75&width=1024",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Multivitamin Capsules",
    category: "Supplements",
    price: 20.0,
    description:
      "Daily multivitamin supplement to support overall health and immunity.",
    brand: "NutriPlus",
    stock: 300,
    image_url:
      "https://nutricost.com/cdn/shop/products/nutricost-multivitamin-capsules-822075_2048x.jpg?v=1698109838",
    rating: 4.3,
  },
  {
    id: 6,
    name: "Resistance Bands Set",
    category: "Accessories",
    price: 15.0,
    description:
      "Set of 5 resistance bands with varying resistance levels, ideal for strength and flexibility exercises.",
    brand: "FitFort",
    stock: 120,
    image_url:
      "https://i5.walmartimages.com/seo/Resistance-Bands-Exercise-Workout-Up-150lb-Indoor-Outdoor-Door-Anchor-Handles-Strength-Slim-Yoga-Home-Gym-Equipment-Men-Women_4f682015-1e1c-4371-8082-814d8ee1e409.4b8b3429e61cfa6ea1f3dfc4ff805ac3.jpeg",
    rating: 4.4,
  },
  {
    id: 7,
    name: "Gym Gloves",
    category: "Accessories",
    price: 10.0,
    description:
      "Comfortable and durable gloves to protect hands during weight lifting.",
    brand: "GripMaster",
    stock: 80,
    image_url: "https://i.ebayimg.com/images/g/wq8AAOSw785j6~iy/s-l1200.jpg",
    rating: 4.2,
  },
  {
    id: 8,
    name: "Fitness Tracker Watch",
    category: "Accessories",
    price: 60.0,
    description:
      "Smart fitness tracker with heart rate monitor, step counter, and calorie tracker.",
    brand: "FitTech",
    stock: 40,
    image_url: "https://m.media-amazon.com/images/I/71R3wk0QavL.jpg",
    rating: 4.5,
  },
  {
    id: 9,
    name: "Treadmill",
    category: "Equipment",
    price: 700.0,
    description:
      "High-quality treadmill with adjustable speeds and incline settings for effective cardio workouts.",
    brand: "CardioMax",
    stock: 10,
    image_url:
      "https://www.soletreadmills.com/cdn/shop/files/SOLE-F85-20230330-9307.jpg?v=1689096438&width=5472",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Cycling Shorts",
    category: "Apparel",
    price: 25.0,
    description: "Comfortable cycling shorts with padded seat.",
    brand: "Rapha",
    stock: 60,
    image_url:
      "https://media.rapha.cc/image/upload/ar_1:1,c_fill,f_auto,q_auto,w_480,dpr_2.0/v1670934756/mannequin/COH02XX_BBK_mens-core-short_H222_mannequin_01.jpg",
    rating: 4.6,
  },
  {
    id: 11,
    name: "Kettlebell - 20 lbs",
    category: "Equipment",
    price: 35.0,
    description:
      "Cast iron kettlebell, 20 lbs, ideal for full-body workouts and strength training.",
    brand: "IronCore",
    stock: 60,
    image_url: "https://www.kroger.com/product/images/large/back/0084236412663",
    rating: 4.6,
  },
  {
    id: 12,
    name: "Pre-Workout Powder",
    category: "Supplements",
    price: 30.0,
    description:
      "Energizing pre-workout powder with caffeine, beta-alanine, and creatine.",
    brand: "Outwork Nutrition ",
    stock: 100,
    image_url:
      "https://outworknutrition.com/cdn/shop/files/PreWorkout-PC-front-fruit-1500px_2048x.jpg?v=1717774803",
    rating: 4.4,
  },
  {
    id: 13,
    name: "Protein Bars (12 Pack)",
    category: "Supplements",
    price: 25.0,
    description:
      "12-pack of protein bars, each containing 20g of protein, chocolate flavor.",
    brand: "Pure Protein",
    stock: 90,
    image_url:
      "https://m.media-amazon.com/images/I/71dKVTOZd5L._AC_UF894,1000_QL80_.jpg",
    rating: 4.5,
  },
  {
    id: 14,
    name: "Sports Water Bottle - 1L",
    category: "Accessories",
    price: 12.0,
    description: "1-liter BPA-free sports water bottle with leak-proof cap.",
    brand: "H2O",
    stock: 150,
    image_url:
      "https://cdn.shopify.com/s/files/1/1367/5207/products/1LWaterBottleBlack-I2A6T-BBBB21.jpg?v=1673514743",
    rating: 4.3,
  },
  {
    id: 15,
    name: "Pull-Up Bar",
    category: "Equipment",
    price: 40.0,
    description: "Doorway pull-up bar for upper body workouts.",
    brand: "AmStaff Fitness",
    stock: 70,
    image_url:
      "https://m.media-amazon.com/images/I/612ZnMLYUvL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.7,
  },
  {
    id: 16,
    name: "Compression Leggings",
    category: "Apparel",
    price: 35.0,
    description: "High-quality compression leggings for support and comfort.",
    brand: "2XU",
    stock: 50,
    image_url:
      "https://us.2xu.com/cdn/shop/files/MA3849b_BLK-NRO_1_d4i9at.jpg?v=1721009162",
    rating: 4.6,
  },
  {
    id: 17,
    name: "Ab Roller",
    category: "Equipment",
    price: 20.0,
    description: "Ab roller for effective core workouts.",
    brand: "AlphaFit",
    stock: 100,
    image_url:
      "https://www.alphafit.com.au/assets/full/52791.jpg?20230131084926",
    rating: 4.4,
  },
  {
    id: 18,
    name: "Protein Shaker Bottle",
    category: "Accessories",
    price: 15.0,
    description: "BPA-free protein shaker bottle with a mixing ball.",
    brand: "ShakeIt",
    stock: 200,
    image_url: "https://m.media-amazon.com/images/I/51vLQLp7A1L.jpg",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Foam Roller",
    category: "Equipment",
    price: 15.0,
    description: "High-density foam roller for muscle recovery and mobility.",
    brand: "York",
    stock: 120,
    image_url:
      "https://yorkbarbell.com/wp-content/uploads/2024/05/82030-Foam-Roller.jpg",
    rating: 4.6,
  },
  {
    id: 20,
    name: "Exercise Ball",
    category: "Equipment",
    price: 20.0,
    description: "65cm exercise ball for core strength and balance.",
    brand: "Life Fitness",
    stock: 90,
    image_url:
      "https://shop.lifefitness.com/cdn/shop/products/stability-ball-65cm-blue-1000x1000_1200x1200.jpg?v=1660657829",
    rating: 4.5,
  },
  {
    id: 21,
    name: "Gym Towel Set",
    category: "Accessories",
    price: 5.0,
    description: "Absorbent gym towel for wiping sweat.",
    brand: "Vivote",
    stock: 300,
    image_url:
      "https://m.media-amazon.com/images/I/71i5RoxXdxL._AC_UF894,1000_QL80_.jpg",
    rating: 4.2,
  },
  {
    id: 22,
    name: "Gym Bag",
    category: "Accessories",
    price: 25.0,
    description: "Spacious gym bag with multiple compartments.",
    brand: "GYM SHARK",
    stock: 80,
    image_url:
      "https://cdn.shopify.com/s/files/1/0156/6146/files/EverydayHoldallBlack-SMALL-I3A1V-BBBB35.jpg?v=1717097805",
    rating: 4.7,
  },
  {
    id: 23,
    name: "Skipping Rope",
    category: "Equipment",
    price: 10.0,
    description: "Adjustable speed skipping rope for cardio workouts.",
    brand: "Sienna",
    stock: 150,
    image_url:
      "https://www.modernrelik.com/cdn/shop/files/SIENNA1_1400x_1baa604f-041b-4fd5-8bf2-43d959e1a775_920x920_crop_center.jpg?v=1696260296",
    rating: 4.5,
  },
  {
    id: 24,
    name: "Ankle Weights - 5 lbs",
    category: "Equipment",
    price: 18.0,
    description: "Adjustable ankle weights for resistance training.",
    brand: "Cap",
    stock: 100,
    image_url:
      "https://i5.walmartimages.com/seo/CAP-5-LB-Pair-Ankle-Wrist-Weights-2-5-LB-Each_b39bb92a-08c5-48d4-97ad-e6975eccae7e_1.8db7239c34ba8ee8d2cbb24be1ce6d61.jpeg?odnHeight=50px&odnWidth=50px&odnBg=FFFFFF",
    rating: 4.4,
  },
  {
    id: 25,
    name: "Leg Press Machine",
    category: "Equipment",
    price: 900.0,
    description: "Commercial-grade leg press machine for lower body strength.",
    brand: "Life Fitness",
    stock: 5,
    image_url:
      "https://gym-experts.com/cdn/shop/products/LFSSLegPress-2_2000x.jpg?v=1486325767",
    rating: 4.9,
  },
  {
    id: 26,
    name: "Massage Gun",
    category: "Accessories",
    price: 100.0,
    description: "Handheld massage gun for deep tissue muscle relief.",
    brand: "APHERMA",
    stock: 40,
    image_url: "https://m.media-amazon.com/images/I/712UHB03CbL.jpg",
    rating: 4.8,
  },
  {
    id: 27,
    name: "Elliptical Machine",
    category: "Equipment",
    price: 500.0,
    description: "Elliptical machine with adjustable resistance levels.",
    brand: "Solo",
    stock: 15,
    image_url:
      "https://www.soletreadmills.com/cdn/shop/files/SOLE-E25-20230109-7905.jpg?v=1689097229&width=1000",
    rating: 4.6,
  },
];
